USE [UTStats]
GO

/****** Object:  Table [dbo].[GAMES]    Script Date: 10/09/2014 14:46:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GAMES](
	[GAME_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GAME_NAME] [nvarchar](50) NULL,
	[GAME_MAP] [nvarchar](50) NULL,
	[GAME_DATE] [datetime] NULL,
	[GAME_LENGTH] [int] NULL,
	[GAME_END] [nvarchar](50) NULL,
	[FRAG_LIMIT] [int] NULL,
	[TIME_LIMIT] [int] NULL,
 CONSTRAINT [PK_GAMES] PRIMARY KEY CLUSTERED 
(
	[GAME_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[PLAYED](
	[PLAYED_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GAME_ID] [bigint] NULL,
	[PLAYER_NAME] [nvarchar](50) NULL,
	[PLAY_TIME] [int] NULL,
 CONSTRAINT [PK_PLAYED] PRIMARY KEY CLUSTERED 
(
	[PLAYED_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[KILLS](
	[KILL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GAME_ID] [bigint] NULL,
	[GAME_TIME] [int] NULL,
	[KILLER] [nvarchar](50) NULL,
	[VICTIM] [nvarchar](50) NULL,
	[WEAPON] [nvarchar](50) NULL,
	[SUICIDE] [nchar](10) NULL,
 CONSTRAINT [PK_KILLS] PRIMARY KEY CLUSTERED 
(
	[KILL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[ITEMS](
	[ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[GAME_ID] [bigint] NULL,
	[GAME_TIME] [int] NULL,
	[PLAYER] [nvarchar](50) NULL,
	[ITEM_TYPE] [nvarchar](50) NULL,
 CONSTRAINT [PK_ITEMS] PRIMARY KEY CLUSTERED 
(
	[ITEM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[LOGFILES](
	[LOGFILE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGFILE_PATH] [text] NULL,
 CONSTRAINT [PK_LOGFILES] PRIMARY KEY CLUSTERED 
(
	[LOGFILE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
